Added terraform example for windows support beta
dcos-terraform/examples pull request #12
Opened 2020-02-07 18:28 UTC by vadymzagorodko

Prepare terraform example to spin up of DCOS Mixed OS cluster in Azure

2020-02-07 18:33 UTC, vadymzagorodko commented
DCOS_OSS-5861: WIndows Beta support - Prepared terraform example to spin up of DCOS Mixed OS cluster in Azure. 
https://jira.d2iq.com/browse/DCOS_OSS-5861

2020-02-07 18:35 UTC, vadymzagorodko commented
@fatz ,@sebbrandt87
please review/approve/merge

2020-02-10 10:16 UTC, fatz requested changes
please run `terraform fmt`

2020-02-10 14:00 UTC, fatz approved these changes

2020-02-10 14:00 UTC, merged