Respective changes as result of released windows-instance module
dcos-terraform/examples pull request #6
Opened 2019-07-25 10:38 UTC by sergiimatusEPAM

1) Added correct Docker image with Ansible changes for Windows Agent 
2) Removed Terraformfile 
3) Updated README.md to avoid link to custom Mesosphere's `./terraform` package

2019-07-25 10:40 UTC, sergiimatusEPAM commented
@sebbrandt87 , @fatz , please review/comment/approve, once you have free time

2019-07-26 07:52 UTC, sebbrandt87 requested changes

2019-07-26 07:52 UTC, sebbrandt87 commented on .gitignore
> +**/.idea/*
missing line break

2019-07-26 07:52 UTC, sebbrandt87 commented on README.md
> +  - [Windows-agent](aws/windows-agent) - An  example with  windows agent support
please move it to the end of the AWS list

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/README.md
> +which is fully integrated into the terraform apply process.
extra space?
also what changed here in the lines? 😕

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/main.tf
> -  version = "~> 0.2.0"
the pessimistic version constraint is correct

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/main.tf
> -
please keep these lines as is

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/main.tf
> -module "winagent" {
the module name here is `winagent` and should stay like this entirely.
a module name does not need to match the source it is created from.

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/main.tf
> +  version = ">= 0.0.1"
a pessimistic version constraint like `~> 0.0.1` would match any "alpha" version and would exclude higher versions like `0.1.0` or `0.2.0` etc.

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/README.md
> -```
I would say keep the spin up instructions from line incl 10 to line incl 16.

2019-07-26 07:52 UTC, sebbrandt87 commented on aws/windows-agent/README.md
> +In order to get Windows instance span up, use latest `main.tf` and specify number of Windows Agents at `num` field.
In order to spin up a DC/OS cluster with extra Windows agents, use the latest `main.tf` and specify number of Windows Agents at `num` field.

2019-08-19 07:18 UTC, sebbrandt87 commented
updated feature branch

2019-08-19 07:18 UTC, closed without merging